[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sono-satellit"
version = "0.1.0"
description = "Scans abdominal sonographic images and measures the thickness of the subcutaneous adipose tissue."
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10"
authors = [
  { name = "Yash Bachhav", email = "yashbachhav03@gmail.com" },
  { name = "Anja Sedlmeier", email = "anja.sedlmeier@ukr.de" },
  { name = "Florian Lüke", email = "florian.lueke@ukr.de" },
  { name = "Sven Seeberg", email = "mail@sven-seeberg.de" },
]
dependencies = [
  "opencv-python",
  "numpy",
  "matplotlib",
  "pydicom",
]

[tool.hatch.build.targets.wheel]
packages = ["sono_satellit"]
